name = "KernelCompiler"
uuid = "74110905-49e5-4c86-8e18-cc3646b459d6"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
Compiler = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
CompilerCaching = "9db33cc3-5358-4881-8759-fa4194144afd"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[compat]
Compiler = "0.1.1"
CompilerCaching = "0.1.2"
LLVM = "9.4.6"
